export const FETCH_LOCACTION_SUCCESS = 'FETCH_LOCACTION_SUCCESS'
export const FETCH_5DAY3HOUR_SUCCESS = 'FETCH_5DAY3HOUR_SUCCESS'
export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS"
export const FETCH_ERROR = 'FETCH_ERROR'